### ISSUE TITLE
Ordering of patterns in the body

### ISSUE THREAD

**Issue by madgen** [lu-cs-sde/metadl#2]
So it seems that if I have multiple atoms in the body of a pattern, the syntactic ordering of atoms in the pattern is ignored, e.g.,

```
Hello(predName1,$ix1,predName2,$ix2) :-
    <: ... :- ..., $pred1(...,$ix1:$x,...),
              ..., $pred2(...,$ix2:$y,...),... .:>,
    ID($pred1,predName1), ID($pred2,predName2), ID($x,varName), ID($y,varName).
```
analysing
```
Ancestor(x,z) :- Parent(x,y), Ancestor(y,z).
```
matches
```
(Parent,0,Parent,0)
(Parent,1,Parent,1)
(Ancestor,0,Ancestor,0)
(Ancestor,1,Ancestor,1)
(Parent,1,Ancestor,0)
(Ancestor,0,Parent,1)
```

If I add `LT($pred1,$pred2)`, I seem to be able to get the desired result only that is `(Parent,1,Ancestor,0)`.

I realise that this relies on assignment of node ids. Is this reliable?

**Comment by alexdura** [comment]
No, assignment of node ids is not reliable. The solution is to introduce two indices and compare them instead:
` <: ... :- ..., $ip1:$pred1(...,$ix1:$x,...),
              ..., $ip2:$pred2(...,$ix2:$y,...),... .:>, LT($ip1, $ip2)`

**Comment by madgen** [comment]
Ah, I didn't realise I could assign indices to predicates as well. Thank you!
